/* 主程序：界面、数据保存、课表重复、统计都在这里。数据只保存在本设备。 */
const PAPER_STAGES=['选题','研究问题','文献搜索','文献阅读','文献整理','论文框架','初稿','修改','引文核对','定稿'];
const TYPE={course:['课程','📚'],paper:['论文','📝'],reading:['阅读','📖'],fitness:['健身','🍑'],other:['其他','•']};
const key='zhixu-pwa-v1';
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=()=>iso(new Date());
const seed=()=>({tasks:[],paperProjects:[{id:'p1',title:'唐代里坊制下的空间权力研究',kind:'毕业论文',stage:'文献搜索'}],books:[{id:'b1',title:'规训与惩罚',author:'米歇尔·福柯',total:350,current:120}],workoutRecords:[],readingRecords:[],reviews:[],cancelledCourses:[]});
let db=Object.assign(seed(),JSON.parse(localStorage.getItem(key)||'{}'));
const save=()=>localStorage.setItem(key,JSON.stringify(db));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mondayOf(d=new Date()){const x=new Date(d);const n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x}
function isCourseActive(date){const d=new Date(date+'T12:00');const s=new Date(APP_CONFIG.semester.start+'T12:00');const weeks=Math.floor((d-s)/604800000)+1;return weeks>=1&&weeks<=APP_CONFIG.semester.weeks}
function coursesFor(date){if(!isCourseActive(date))return[];const wd=new Date(date+'T12:00').getDay();return APP_CONFIG.courses.filter(c=>c.weekday===wd&&!db.cancelledCourses.includes(`${c.id}:${date}`)).map(c=>({...c,type:'course',date,notes:`${c.place} · ${c.teacher}`,fixed:true,done:false}))}
function tasksFor(date){return [...coursesFor(date),...db.tasks.filter(t=>t.date===date)].sort((a,b)=>a.start.localeCompare(b.start))}
function duration(t){return Number(t.actualMinutes||t.minutes||Math.max(0,(+t.end.slice(0,2)*60 + +t.end.slice(3))-(+t.start.slice(0,2)*60 + +t.start.slice(3))))}
function taskHtml(t){return `<div class="task" data-type="${t.type}"><div class="task-time">${esc(t.start)}${t.end?`<br>${esc(t.end)}`:''}</div><i class="task-bar"></i><div><h3>${TYPE[t.type][1]} ${esc(t.title)}</h3><p>${esc(t.notes||`${duration(t)} 分钟`)}</p>${!t.fixed?`<div class="small-actions"><button data-edit="${t.id}">编辑</button><button data-move="${t.id}">移到明天</button><button data-delete="${t.id}">删除</button></div>`:`<div class="small-actions"><button data-cancel-course="${t.id}" data-date="${t.date}">本次取消</button></div>`}</div>${t.fixed?'':`<button class="check ${t.done?'done':''}" data-check="${t.id}" aria-label="切换完成状态">${t.done?'✓':''}</button>`}</div>`}
function todayView(){const date=today(),items=tasksFor(date),user=items.filter(x=>!x.fixed),done=user.filter(x=>x.done).length,pct=user.length?Math.round(done/user.length*100):0;return `<section class="hero"><p class="muted">今日完成度</p><h2>${done} / ${user.length} 项 · ${pct}%</h2><div class="progress"><i style="width:${pct}%"></i></div></section><div class="grid"><div class="card metric"><span class="muted">论文投入</span><strong>${mins(user,'paper')}m</strong></div><div class="card metric"><span class="muted">阅读投入</span><strong>${mins(user,'reading')}m</strong></div></div><div class="section-title"><h2>时间线</h2><button class="text-button" data-auto>自动安排</button></div><section class="card">${items.length?items.map(taskHtml).join(''):'<div class="empty">今天还没有安排，点击右上角＋开始。</div>'}</section><section class="card"><div class="section-title"><h2>快捷入口</h2></div><div class="tabs"><button data-route-go="reading">阅读书架</button><button data-review>今日复盘</button><button data-focus>开始论文 25 分钟</button></div><div id="focusArea"></div></section>`}
function weekView(){const m=mondayOf(),days=[...Array(7)].map((_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d});return `<section class="week-grid">${days.map((d,i)=>{const date=iso(d),ts=tasksFor(date);return `<article class="card day ${date===today()?'today':''}"><h3>周${'一二三四五六日'[i]} · ${d.getMonth()+1}/${d.getDate()}</h3>${ts.map(t=>`<span class="chip ${t.type}">${esc(t.start)} ${TYPE[t.type][1]} ${esc(t.title)}</span>`).join('')||'<p class="muted">留白日</p>'}</article>`}).join('')}</section>`}
function papersView(){return `<div class="section-title"><h2>论文项目</h2><button class="text-button" data-add-paper>＋ 新建</button></div>${db.paperProjects.map(p=>`<article class="card"><div class="project-head"><div><p class="muted">${esc(p.kind)}</p><h2>${esc(p.title)}</h2></div><span class="stage">${esc(p.stage)}</span></div><div class="small-actions"><button data-paper-task="${p.id}">安排今日任务</button><button data-paper-stage="${p.id}">推进阶段</button><button data-paper-delete="${p.id}">删除项目</button></div></article>`).join('')||'<div class="empty">还没有论文项目。</div>'}<div class="section-title"><h2>阅读书架</h2><button class="text-button" data-add-book>＋ 添加</button></div>${db.books.map(bookHtml).join('')}`}
function bookHtml(b){const pct=Math.min(100,Math.round(b.current/b.total*100));return `<article class="card"><div class="book-head"><div><h3>《${esc(b.title)}》</h3><p class="muted">${esc(b.author)}</p></div><strong>${pct}%</strong></div><div class="book-progress"><i style="width:${pct}%"></i></div><p>${b.current} / ${b.total} 页</p><div class="small-actions"><button data-log-reading="${b.id}">记录阅读</button><button data-book-delete="${b.id}">删除</button></div></article>`}
function fitnessView(){const m=mondayOf(),count=db.tasks.filter(t=>t.type==='fitness'&&t.done&&new Date(t.date)>=m).length,g=APP_CONFIG.workoutGoal;let msg=count<g.min?`本周训练 ${count} 次，距离最低目标还有 ${g.min-count} 次。`:count<g.recommended?'本周最低训练目标已完成。':count<g.max?'本周推荐训练目标已完成。':'本周训练目标已全部完成。';return `<section class="hero"><p class="muted">本周训练</p><h2>${count} / ${g.recommended} 次</h2><p>${msg}</p></section><div class="section-title"><h2>训练模板</h2></div><div class="grid">${APP_CONFIG.workoutTemplates.map((w,i)=>`<article class="card template"><h3>${w.name}</h3><ul>${w.items.map(x=>`<li>${x}</li>`).join('')}</ul><button class="primary" data-schedule-workout="${i}">安排训练</button></article>`).join('')}</div>`}
function mins(items,type){return items.filter(t=>t.type===type&&t.done).reduce((a,t)=>a+duration(t),0)}
function statsView(){const m=mondayOf(),items=db.tasks.filter(t=>t.done&&new Date(t.date)>=m),paper=mins(items,'paper'),reading=mins(items,'reading'),fitness=items.filter(t=>t.type==='fitness').length,total=paper+reading,pct=total?paper/total:0,target=APP_CONFIG.ratio.paper/(APP_CONFIG.ratio.paper+APP_CONFIG.ratio.reading),ok=Math.abs(pct-target)<.12,status=!total?'完成论文或阅读任务后，这里会给出比例建议。':ok?'✓ 时间分配合理':pct<target?'⚠ 当前论文投入不足，下一次空闲时间建议优先安排论文。':'⚠ 本周阅读比例偏低，建议安排一次兴趣或理论阅读。';return `<div class="grid three"><div class="card metric"><span class="muted">论文</span><strong>${(paper/60).toFixed(1)}h</strong></div><div class="card metric"><span class="muted">阅读</span><strong>${(reading/60).toFixed(1)}h</strong></div><div class="card metric"><span class="muted">健身</span><strong>${fitness}次</strong></div></div><article class="card"><h2>学术时间分配</h2><div class="ratio"><i class="paper" style="width:${total?paper/total*100:75}%"></i><i class="reading" style="width:${total?reading/total*100:25}%"></i></div><p>阅读 : 论文 = ${reading?`1 : ${(paper/reading).toFixed(1)}`:'暂无完整数据'}（目标 1 : ${APP_CONFIG.ratio.paper}）</p><div class="notice">${status}</div></article><article class="card"><h2>数据说明</h2><p class="muted">统计使用本周已完成任务的实际分钟数；未填写实际时间时使用预计分钟数。所有数据仅保存在当前浏览器。</p><button class="text-button" data-export>导出数据备份</button></article>`}
function readingView(){return `<div class="section-title"><h2>我的书架</h2><button class="text-button" data-add-book>＋ 添加书籍</button></div>${db.books.map(bookHtml).join('')||'<div class="empty">还没有书籍。</div>'}`}
const titles={today:'今日计划',week:'本周安排',papers:'论文与阅读',fitness:'健身计划',stats:'统计',reading:'阅读'};
function render(){const route=location.hash.slice(1)||'today';document.querySelector('#pageTitle').textContent=titles[route]||titles.today;document.querySelector('#dateLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());document.querySelector('#app').innerHTML=({today:todayView,week:weekView,papers:papersView,fitness:fitnessView,stats:statsView,reading:readingView}[route]||todayView)();document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route));bind()}
function openTask(prefill={}){const f=document.querySelector('#taskForm');f.reset();f.id.value=prefill.id||'';f.type.value=prefill.type||'paper';f.title.value=prefill.title||'';f.date.value=prefill.date||today();f.start.value=prefill.start||'09:00';f.minutes.value=prefill.minutes||60;f.priority.value=prefill.priority||'中';f.notes.value=prefill.notes||'';document.querySelector('#dialogTitle').textContent=prefill.id?'编辑任务':'新增任务';document.querySelector('#taskDialog').showModal()}
function bind(){document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const t=db.tasks.find(x=>x.id===b.dataset.check);t.done=!t.done;t.actualMinutes=t.done?t.minutes:0;save();render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除这个任务？')){db.tasks=db.tasks.filter(x=>x.id!==b.dataset.delete);save();render()}});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openTask(db.tasks.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const t=db.tasks.find(x=>x.id===b.dataset.move),d=new Date(t.date+'T12:00');d.setDate(d.getDate()+1);t.date=iso(d);t.postponed=(t.postponed||0)+1;save();alert(t.postponed>=3?'这个任务已经连续推迟3次，建议拆分任务或重新安排。':'已移到明天');render()});document.querySelectorAll('[data-cancel-course]').forEach(b=>b.onclick=()=>{db.cancelledCourses.push(`${b.dataset.cancelCourse}:${b.dataset.date}`);save();render()});document.querySelectorAll('[data-route-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.routeGo);document.querySelector('[data-auto]')?.addEventListener('click',autoSchedule);document.querySelector('[data-add-paper]')?.addEventListener('click',()=>document.querySelector('#paperDialog').showModal());document.querySelectorAll('[data-add-book]').forEach(b=>b.onclick=()=>document.querySelector('#bookDialog').showModal());document.querySelectorAll('[data-paper-task]').forEach(b=>{b.onclick=()=>{const p=db.paperProjects.find(x=>x.id===b.dataset.paperTask);openTask({type:'paper',title:`${p.stage}：${p.title}`,minutes:90})}});document.querySelectorAll('[data-paper-stage]').forEach(b=>b.onclick=()=>{const p=db.paperProjects.find(x=>x.id===b.dataset.paperStage),i=PAPER_STAGES.indexOf(p.stage);p.stage=PAPER_STAGES[Math.min(i+1,PAPER_STAGES.length-1)];save();render()});document.querySelectorAll('[data-paper-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除项目？')){db.paperProjects=db.paperProjects.filter(x=>x.id!==b.dataset.paperDelete);save();render()}});document.querySelectorAll('[data-log-reading]').forEach(b=>b.onclick=()=>logReading(b.dataset.logReading));document.querySelectorAll('[data-book-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除书籍？')){db.books=db.books.filter(x=>x.id!==b.dataset.bookDelete);save();render()}});document.querySelectorAll('[data-schedule-workout]').forEach(b=>b.onclick=()=>openTask({type:'fitness',title:APP_CONFIG.workoutTemplates[+b.dataset.scheduleWorkout].name,start:'19:00',minutes:75,notes:APP_CONFIG.workoutTemplates[+b.dataset.scheduleWorkout].items.join('；')}));document.querySelector('[data-export]')?.addEventListener('click',exportData);document.querySelector('[data-review]')?.addEventListener('click',review);document.querySelector('[data-focus]')?.addEventListener('click',startFocus)}
function autoSchedule(){const date=today(),existing=tasksFor(date);if(db.tasks.some(t=>t.date===date&&!t.done)){alert('今天已有待完成任务，已保留当前安排。');return}const slots=['09:00','14:00','16:00','19:00'];const occupied=s=>existing.some(t=>Math.abs((+t.start.slice(0,2)*60 + +t.start.slice(3))-(+s.slice(0,2)*60 + +s.slice(3)))<100);const add=(type,title,minutes)=>{const start=slots.find(s=>!occupied(s)&&!db.tasks.some(t=>t.date===date&&t.start===s));if(start)db.tasks.push({id:uid(),type,title,date,start,minutes,priority:'中',notes:'自动排程',done:false})};add('paper','推进当前论文任务',90);add('paper','整理材料或修改章节',90);add('reading','阅读计划',60);add('fitness','臀腿 / 爬坡训练',75);save();render()}
function logReading(id){const b=db.books.find(x=>x.id===id),from=b.current,end=Number(prompt(`当前第 ${from} 页，本次读到第几页？`,from+20));if(!end||end<from)return;const minutes=Number(prompt('本次阅读多少分钟？','45'))||45;db.readingRecords.push({id:uid(),bookId:id,date:today(),from,to:end,minutes});b.current=Math.min(end,b.total);db.tasks.push({id:uid(),type:'reading',title:`阅读《${b.title}》${end-from}页`,date:today(),start:new Date().toTimeString().slice(0,5),minutes,actualMinutes:minutes,priority:'中',notes:`读至 ${end} 页`,done:true});save();render()}
function review(){const result=prompt('今日复盘：最重要的成果、未完成原因和明日三件事');if(result){db.reviews=db.reviews.filter(x=>x.date!==today());db.reviews.push({date:today(),text:result});save();alert('复盘已保存')}}
let timer;function startFocus(){let left=25*60;const el=document.querySelector('#focusArea');clearInterval(timer);timer=setInterval(()=>{left--;el.textContent=`论文专注 ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(timer);db.tasks.push({id:uid(),type:'paper',title:'论文专注',date:today(),start:new Date().toTimeString().slice(0,5),minutes:25,actualMinutes:25,priority:'中',notes:'专注计时完成',done:true});save();render();alert('专注完成，已计入论文时间。')}},1000)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`知序备份-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#quickAdd').onclick=()=>openTask();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));o.minutes=Number(o.minutes);o.done=false;if(o.id){Object.assign(db.tasks.find(x=>x.id===o.id),o)}else{o.id=uid();db.tasks.push(o)}save();e.currentTarget.closest('dialog').close();render()};document.querySelector('#paperForm [name=stage]').innerHTML=PAPER_STAGES.map(x=>`<option>${x}</option>`).join('');document.querySelector('#paperForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));o.id=uid();db.paperProjects.push(o);save();e.currentTarget.closest('dialog').close();render()};document.querySelector('#bookForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));o.id=uid();o.total=Number(o.total);o.current=Number(o.current);db.books.push(o);save();e.currentTarget.closest('dialog').close();render()};window.addEventListener('hashchange',render);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();

